version: "3.7"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app/backend
    ports:
      - 8000:8000
    env_file: ./backend/.env
    depends_on:
      - db

  db:
    image: postgres
    env_file: ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    depends_on:
      - "backend"
    command: yarn start
